version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: dj-starter:slim-0.1.0
    restart: always
    environment:
      - LANG=C.UTF-8
      - DJANGO_ENV=prod
    volumes:
      - .:/opt/server
    networks:
      - web_nw
      - db_nw
    depends_on:
      - db
    command:
      ${RUN_CMD:-sh}

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=xxx
    ports:
      - ${DOCKER_DB_PORT:-5432}:5432
    env_file:
      - .env
    networks:
      - db_nw
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data


networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
